/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apiUser;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MainApplication {
    public static void main(String args[]){
        SpringApplication.run(MainApplication.class, args);
    }
}
